export const organisations = [
    {
      "type": "UNIVERSITY",
      "name": "Auburn University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Burnt Orange",
      "secondaryColor": "Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#F26522",
      "secondaryColorHex": "#03244D",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Auburn"
    },
    {
      "type": "UNIVERSITY",
      "name": "Baylor University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Green",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#004834",
      "secondaryColorHex": "#FFB81C",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Baylor"
    },
    {
      "type": "UNIVERSITY",
      "name": "Clemson University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Clemson Orange",
      "secondaryColor": "Regalia",
      "ternaryColor": "White",
      "primaryColorHex": "#F56600",
      "secondaryColorHex": "#522D80",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Clemson"
    },
    {
      "type": "UNIVERSITY",
      "name": "Duke University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "White",
      "ternaryColor": "Navy Blue",
      "primaryColorHex": "#003366",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#001A57",
      "country": "US",
      "shortName": "Duke"
    },
    {
      "type": "UNIVERSITY",
      "name": "Florida State University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Garnet",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#782F40",
      "secondaryColorHex": "#CEB888",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "FSU"
    },
    {
      "type": "UNIVERSITY",
      "name": "Indiana University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Cream",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#EEEEEE",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#808080",
      "country": "US",
      "shortName": "Indiana"
    },
    {
      "type": "UNIVERSITY",
      "name": "Louisiana State University (LSU)",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Purple",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#461D7C",
      "secondaryColorHex": "#FDD023",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "LSU"
    },
    {
      "type": "UNIVERSITY",
      "name": "Michigan State University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Green",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#18453B",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#888888",
      "country": "US",
      "shortName": "MSU"
    },
    {
      "type": "UNIVERSITY",
      "name": "Northwestern University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Purple",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#4E2A84",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#A7A9AC",
      "country": "US",
      "shortName": "Northwestern"
    },
    {
      "type": "UNIVERSITY",
      "name": "Ohio State University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Scarlet",
      "secondaryColor": "Gray",
      "ternaryColor": "White",
      "primaryColorHex": "#BB0000",
      "secondaryColorHex": "#666666",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Ohio State"
    },
    {
      "type": "UNIVERSITY",
      "name": "Oklahoma State University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Orange",
      "secondaryColor": "Black",
      "ternaryColor": "White",
      "primaryColorHex": "#FF7300",
      "secondaryColorHex": "#000000",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Oklahoma State"
    },
    {
      "type": "UNIVERSITY",
      "name": "Pennsylvania State University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#002D72",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#888888",
      "country": "US",
      "shortName": "Penn State"
    },
    {
      "type": "UNIVERSITY",
      "name": "Purdue University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Black",
      "secondaryColor": "Gold",
      "ternaryColor": "Gray",
      "primaryColorHex": "#000000",
      "secondaryColorHex": "#B3995D",
      "ternaryColorHex": "#888888",
      "country": "US",
      "shortName": "Purdue"
    },
    {
      "type": "UNIVERSITY",
      "name": "Stanford University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Cardinal",
      "secondaryColor": "White",
      "ternaryColor": "Black",
      "primaryColorHex": "#8C1515",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#000000",
      "country": "US",
      "shortName": "Stanford"
    },
    {
      "type": "UNIVERSITY",
      "name": "Syracuse University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Orange",
      "secondaryColor": "Navy Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#D44500",
      "secondaryColorHex": "#002D62",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Syracuse"
    },
    {
      "type": "UNIVERSITY",
      "name": "Texas A&M University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Maroon",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#500000",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#888888",
      "country": "US",
      "shortName": "Texas A&M"
    },
    {
      "type": "UNIVERSITY",
      "name": "Texas Tech University",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Red",
      "secondaryColor": "Black",
      "ternaryColor": "Gray",
      "primaryColorHex": "#CC0000",
      "secondaryColorHex": "#000000",
      "ternaryColorHex": "#888888",
      "country": "US",
      "shortName": "Texas Tech"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Alabama",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Crimson",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#9E1B32",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#828282",
      "country": "US",
      "shortName": "Alabama"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Arizona",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Cardinal",
      "secondaryColor": "Navy Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#CC0033",
      "secondaryColorHex": "#003366",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Arizona"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Arkansas",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Cardinal",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#9D2235",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#A7A9AC",
      "country": "US",
      "shortName": "Arkansas"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of California, Berkeley",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#003262",
      "secondaryColorHex": "#FDB515",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "UC Berkeley"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of California, Los Angeles",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#2774AE",
      "secondaryColorHex": "#FFD100",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "UCLA"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Colorado Boulder",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Black",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#000000",
      "secondaryColorHex": "#CFB87C",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Colorado"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Florida",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Orange",
      "secondaryColor": "Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#FA4616",
      "secondaryColorHex": "#0021A5",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Florida"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Georgia",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Red",
      "secondaryColor": "Black",
      "ternaryColor": "White",
      "primaryColorHex": "#BA0C2F",
      "secondaryColorHex": "#000000",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Georgia"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Houston",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Red",
      "secondaryColor": "White",
      "ternaryColor": "Silver",
      "primaryColorHex": "#C8102E",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#A7A9AC",
      "country": "US",
      "shortName": "Houston"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Illinois",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Orange",
      "secondaryColor": "Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#E84A27",
      "secondaryColorHex": "#13294B",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Illinois"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Iowa",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Black",
      "secondaryColor": "Gold",
      "ternaryColor": "Gray",
      "primaryColorHex": "#000000",
      "secondaryColorHex": "#FCD116",
      "ternaryColorHex": "#A7A9AC",
      "country": "US",
      "shortName": "Iowa"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Kansas",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "Crimson",
      "ternaryColor": "White",
      "primaryColorHex": "#0051BA",
      "secondaryColorHex": "#E8000D",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Kansas"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Kentucky",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#0033A0",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#A7A9AC",
      "country": "US",
      "shortName": "Kentucky"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Louisville",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Red",
      "secondaryColor": "Black",
      "ternaryColor": "Gray",
      "primaryColorHex": "#AD0000",
      "secondaryColorHex": "#000000",
      "ternaryColorHex": "#828282",
      "country": "US",
      "shortName": "Louisville"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Maryland",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Red",
      "secondaryColor": "Gold",
      "ternaryColor": "Black",
      "primaryColorHex": "#E03A3E",
      "secondaryColorHex": "#FFD700",
      "ternaryColorHex": "#000000",
      "country": "US",
      "shortName": "Maryland"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Miami",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Orange",
      "secondaryColor": "Green",
      "ternaryColor": "White",
      "primaryColorHex": "#F47321",
      "secondaryColorHex": "#005030",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Miami"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Michigan",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Maize",
      "secondaryColor": "Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#FFCB05",
      "secondaryColorHex": "#00274C",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Michigan"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Minnesota",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Maroon",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#7A0019",
      "secondaryColorHex": "#FFCC33",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Minnesota"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Missouri",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Gold",
      "secondaryColor": "Black",
      "ternaryColor": "White",
      "primaryColorHex": "#F1B82D",
      "secondaryColorHex": "#000000",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Missouri"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Nebraska",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Red",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#D00000",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#828282",
      "country": "US",
      "shortName": "Nebraska"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of North Carolina at Chapel Hill",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Carolina Blue",
      "secondaryColor": "White",
      "ternaryColor": "Navy Blue",
      "primaryColorHex": "#7BAFD4",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#13294B",
      "country": "US",
      "shortName": "UNC"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Notre Dame",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "Gold",
      "ternaryColor": "Green",
      "primaryColorHex": "#002654",
      "secondaryColorHex": "#C99700",
      "ternaryColorHex": "#008000",
      "country": "US",
      "shortName": "Notre Dame"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Oklahoma",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Crimson",
      "secondaryColor": "Cream",
      "ternaryColor": "White",
      "primaryColorHex": "#841617",
      "secondaryColorHex": "#F5DEB3",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Oklahoma"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Oregon",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Green",
      "secondaryColor": "Yellow",
      "ternaryColor": "White",
      "primaryColorHex": "#004B49",
      "secondaryColorHex": "#FEE123",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Oregon"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Pittsburgh",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Gold",
      "secondaryColor": "Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#FFB81C",
      "secondaryColorHex": "#003594",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Pitt"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of South Carolina",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Garnet",
      "secondaryColor": "Black",
      "ternaryColor": "White",
      "primaryColorHex": "#73000A",
      "secondaryColorHex": "#000000",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "South Carolina"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Southern California (USC)",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Cardinal",
      "secondaryColor": "Gold",
      "ternaryColor": "Black",
      "primaryColorHex": "#990000",
      "secondaryColorHex": "#FFCC00",
      "ternaryColorHex": "#000000",
      "country": "US",
      "shortName": "USC"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Tennessee",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Orange",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#FF8200",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#828282",
      "country": "US",
      "shortName": "Tennessee"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Texas at Austin",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Burnt Orange",
      "secondaryColor": "White",
      "ternaryColor": "Black",
      "primaryColorHex": "#BF5700",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#000000",
      "country": "US",
      "shortName": "UT Austin"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Texas at San Antonio",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Orange",
      "secondaryColor": "Blue",
      "ternaryColor": "White",
      "primaryColorHex": "#F15A22",
      "secondaryColorHex": "#0C2340",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "UTSA"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Utah",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Red",
      "secondaryColor": "White",
      "ternaryColor": "Gray",
      "primaryColorHex": "#CC0000",
      "secondaryColorHex": "#FFFFFF",
      "ternaryColorHex": "#828282",
      "country": "US",
      "shortName": "Utah"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Virginia",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Blue",
      "secondaryColor": "Orange",
      "ternaryColor": "White",
      "primaryColorHex": "#232D4B",
      "secondaryColorHex": "#F84C1E",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Virginia"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Washington",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Purple",
      "secondaryColor": "Gold",
      "ternaryColor": "White",
      "primaryColorHex": "#4B2E83",
      "secondaryColorHex": "#B7A57A",
      "ternaryColorHex": "#FFFFFF",
      "country": "US",
      "shortName": "Washington"
    },
    {
      "type": "UNIVERSITY",
      "name": "University of Wisconsin-Madison",
      "league": "NCAA",
      "division": "Division 1",
      "primaryColor": "Cardinal",
      "secondaryColor": "White",
      "ternaryColor": "Black",
      "primaryColorHex": "",
      "secondaryColorHex": "",
      "ternaryColorHex": "",
      "country": "US",
      "shortName": ""
    }
  ]

  export  const teams = [
    {
      "name": "Men's Basketball",
      "gender": "Men",
      "sport": "Basketball"
    },
    {
      "name": "Women's Basketball",
      "gender": "Women",
      "sport": "Basketball"
    },
    {
      "name": "Men's Soccer",
      "gender": "Men",
      "sport": "Soccer"
    },
    {
      "name": "Women's Soccer",
      "gender": "Women",
      "sport": "Soccer"
    },
    {
      "name": "Men's Baseball",
      "gender": "Men",
      "sport": "Baseball"
    },
    {
      "name": "Women's Baseball",
      "gender": "Women",
      "sport": "Baseball"
    },
    {
      "name": "Men's Football",
      "gender": "Men",
      "sport": "Football"
    },
    {
      "name": "Women's Football",
      "gender": "Women",
      "sport": "Football"
    },
    {
      "name": "Men's Swimming",
      "gender": "Men",
      "sport": "Swimming"
    },
    {
      "name": "Women's Swimming",
      "gender": "Women",
      "sport": "Swimming"
    },
    {
      "name": "Men's Tennis",
      "gender": "Men",
      "sport": "Tennis"
    },
    {
      "name": "Women's Tennis",
      "gender": "Women",
      "sport": "Tennis"
    },
    {
      "name": "Men's Track and Field",
      "gender": "Men",
      "sport": "Track and Field"
    },
    {
      "name": "Women's Track and Field",
      "gender": "Women",
      "sport": "Track and Field"
    },
    {
      "name": "Men's Volleyball",
      "gender": "Men",
      "sport": "Volleyball"
    },
    {
      "name": "Women's Volleyball",
      "gender": "Women",
      "sport": "Volleyball"
    },
    {
      "name": "Men's Golf",
      "gender": "Men",
      "sport": "Golf"
    },
    {
      "name": "Women's Golf",
      "gender": "Women",
      "sport": "Golf"
    },
    {
      "name": "Men's Lacrosse",
      "gender": "Men",
      "sport": "Lacrosse"
    },
    {
      "name": "Women's Lacrosse",
      "gender": "Women",
      "sport": "Lacrosse"
    }
]	

const v = [
{
  "tribeId" : "671d44478ea5d6ebb58074ce",
  "userId" : "656803007ee1565fbc47fdc1"
},
{
  "tribeId" : "671d44478ea5d6ebb58074ce",
  "userId" : "6567ffa87ee1565fbc47fdb3"
},
{
  "tribeId" : "671d44478ea5d6ebb58074ce",
  "userId" : "656801147ee1565fbc47fdb8"
},
{
  "tribeId" : "671d44478ea5d6ebb58074ce",
  "userId" : "6568029b7ee1565fbc47fdbf"
},
{
  "tribeId" : "671d44478ea5d6ebb58074ce",
  "userId" : "6567ff717ee1565fbc47fdb2"
},
{
  "tribeId" : "671d44478ea5d6ebb58074ce",
  "userId" : "656b65394c46bdf428a94a46"
},
{
  "tribeId" : "671d44478ea5d6ebb58074ce",
  "userId" : "656b65394c46bdf428a94a46"
}
]